Add cv.empty_config_schema
home-assistant/example-custom-config pull request #57
Opened 2023-09-14 15:56 UTC by shannonfritz

The component does not have any config options, so using cv.empty_config_schema to ensure it passes validation.

2023-09-15 05:32 UTC, MartinHjelmare requested changes

2023-09-15 05:32 UTC, MartinHjelmare commented on custom_components/example_load_platform/__init__.py
> +# The domain of your component. Should be equal to the name of your component.
```suggestion
# The domain of your integration. Should be equal to the name of the directory of your integration.
```

2023-09-15 05:32 UTC, MartinHjelmare commented on custom_components/example_load_platform/__init__.py
> +# Use empty_config_schema because the component does not have any config options
```suggestion
# Use empty_config_schema because the integration does not have any config options
```

2024-06-09 11:38 UTC, frenck commented
Since there was no response at all, I'm declaring this PR stale and closing it.
Feel free to re-open this PR when you feel like that is the appropriate thing to do.

../Frenck

2024-06-09 11:38 UTC, closed without merging