refactor(detailed_hello_world): use custom ConfigEntry runtime_data
home-assistant/example-custom-config pull request #70
Opened 2024-08-16 20:46 UTC by HipsterBrown

Based on the change to the `ConfigEntry` usage described in [this developer docs blog post](https://developers.home-assistant.io/blog/2024/04/30/store-runtime-data-inside-config-entry), integrations can/should extend the `ConfigEntry` type to store custom data as the `runtime_data` field to be accessed by platforms and services associated with that entry. 

This PR updates the `detailed_hello_world_push` example to demonstrate this new pattern.

2024-08-17 21:43 UTC, MartinHjelmare requested changes

2024-08-17 21:43 UTC, MartinHjelmare commented on custom_components/detailed_hello_world_push/cover.py
> +    _hass: HomeAssistant,
```suggestion
    hass: HomeAssistant,
```

2024-08-17 21:43 UTC, MartinHjelmare commented on custom_components/detailed_hello_world_push/sensor.py
> +async def async_setup_entry(_hass, config_entry, async_add_entities):
```suggestion
async def async_setup_entry(hass, config_entry, async_add_entities):
```

2024-08-17 21:43 UTC, MartinHjelmare commented on custom_components/detailed_hello_world_push/sensor.py
> +async def async_setup_entry(_hass, config_entry, async_add_entities):
It would be good to add type annotations here too.

2024-08-20 20:46 UTC, HipsterBrown commented
Thanks for the review, @MartinHjelmare! 👍

2024-08-20 20:59 UTC, MartinHjelmare approved these changes
Thanks!

2024-08-20 21:07 UTC, MartinHjelmare commented
CI failure is unrelated.

2024-08-20 21:07 UTC, merged